let keys = [
    {id: 'q', defaultValue: 'q', shiftedValue: 'Q'},
    {id: 'w', defaultValue: 'w', shiftedValue: 'W'},
    {id: 'e', defaultValue: 'e', shiftedValue: 'E'},
    {id: 'r', defaultValue: 'r', shiftedValue: 'R'},
    {id: 't', defaultValue: 't', shiftedValue: 'T'},
    {id: 'y', defaultValue: 'y', shiftedValue: 'Y'},
    {id: 'u', defaultValue: 'u', shiftedValue: 'U'},
    {id: 'i', defaultValue: 'i', shiftedValue: 'I'},
    {id: 'o', defaultValue: 'o', shiftedValue: 'O'},
    {id: 'p', defaultValue: 'p', shiftedValue: 'P'},
    {id: '[', defaultValue: '[', shiftedValue: '{'},
    {id: ']', defaultValue: ']', shiftedValue: '}'},
    {id: '\\', defaultValue: '\\', shiftedValue: '|'},

    {id: 'a', defaultValue: 'a', shiftedValue: 'A'},
    {id: 's', defaultValue: 's', shiftedValue: 'S'},
    {id: 'd', defaultValue: 'd', shiftedValue: 'D'},
    {id: 'f', defaultValue: 'f', shiftedValue: 'F'},
    {id: 'g', defaultValue: 'g', shiftedValue: 'G'},
    {id: 'h', defaultValue: 'h', shiftedValue: 'H'},
    {id: 'j', defaultValue: 'j', shiftedValue: 'J'},
    {id: 'k', defaultValue: 'k', shiftedValue: 'K'},
    {id: 'l', defaultValue: 'l', shiftedValue: 'L'},
    {id: ';', defaultValue: ';', shiftedValue: ':'},
    {id: "'", defaultValue: "'", shiftedValue: '"'},

    {id: 'z', defaultValue: 'z', shiftedValue: 'Z'},
    {id: 'x', defaultValue: 'x', shiftedValue: 'X'},
    {id: 'c', defaultValue: 'c', shiftedValue: 'C'},
    {id: 'v', defaultValue: 'v', shiftedValue: 'V'},
    {id: 'b', defaultValue: 'b', shiftedValue: 'B'},
    {id: 'n', defaultValue: 'n', shiftedValue: 'N'},
    {id: 'm', defaultValue: 'm', shiftedValue: 'M'},
    {id: ',', defaultValue: ',', shiftedValue: '<'},
    {id: '.', defaultValue: '.', shiftedValue: '>'},
    {id: '/', defaultValue: '/', shiftedValue: '?'},

    { id: '~', defaultValue: '`', shiftedValue: '~' },
    { id: '1', defaultValue: '1', shiftedValue: '!' },
    { id: '2', defaultValue: '2', shiftedValue: '@' },
    { id: '3', defaultValue: '3', shiftedValue: '#' },
    { id: '4', defaultValue: '4', shiftedValue: '$' },
    { id: '5', defaultValue: '5', shiftedValue: '%' },
    { id: '6', defaultValue: '6', shiftedValue: '^' },
    { id: '7', defaultValue: '7', shiftedValue: '&' },
    { id: '8', defaultValue: '8', shiftedValue: '*' },
    { id: '9', defaultValue: '9', shiftedValue: '(' },
    { id: '0', defaultValue: '0', shiftedValue: ')' },
    { id: '-', defaultValue: '-', shiftedValue: '_' },
    { id: '=', defaultValue: '=', shiftedValue: '+' },
]

export { keys };